[redis]
host='localhost'
port=6379
db=1
username='root'
password='123456'
expires=600

[minio]
endpoint='xxx'
access_key='xxx'
secret_key='xxx'
bucket_name='xxx'


[tortoise]
url='sqlite://./resource/db.sqlite3'
modules=[
    'src.model.entity.user'
]

[fastapi]
session_key='xxx'

[fastapi.jwt]
expires=10
algorithm='HS256'
secret_key='xxxx'
token_key='Authorization1'

